import './globals.css'

export const metadata = {
  title: 'Linktree App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='text-white' >{children}</body>
    </html>
  )
}

